version: '3'
services:
  db:
    image: mysql/mysql-server:latest
    restart: always
    environment:
      MYSQL_DATABASE: db/development.sqlite3
    ports: 
      - "3306"
    expose:
      - "3306"
  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/Practise
    ports:
      - "3000:3000"
    depends_on:
      - db
    container_name: practise_app
